name: "wiz-cli"
on:
  pull_request:
  workflow_dispatch:

jobs:
  wiz-cli-scan:
    name: "Wiz-cli Scan"
    runs-on: ubuntu-latest
    env:
      SECRETS_POLICY: "Demo GitLab Secrets Policy"
      VULN_POLICY: "Demo GitLab Vuln Policy"

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download Wiz CLI
        run: curl -o wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

      - name: Run Wiz CLI scan
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
        run: |
          ./wizcli scan dir . \
            -p "$SECRETS_POLICY" \
            -p "$VULN_POLICY" \
            --name="${{ github.event.repository.name }}-${{ github.run_id }}" \
            --by-policy-hits="DISABLED" \
            --json-output-file=wiz-scan-results.json \
            --sbom-output-file=wiz-sbom.json

      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wiz-scan-results
          path: wiz-scan-results.json

      - name: Upload SBOM
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wiz-sbom
          path: wiz-sbom.json
